---
apiVersion: apps/v1
kind: Deployment
metadata:
  # Chnage name and label
  name: nginx
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      # Chnage label
      app: nginx
  template:
    metadata:
      labels:
        # Chnage label
        app: nginx
    spec:
      containers:
        - name: nginx
          # Change container image
          image: nginx:latest
          ports:
            - containerPort: 80
