---
apiVersion: apps.utho.com/v1alpha1
kind: UthoApplication
metadata:
  # Chnage name
  name: nginx
  # Chnage namespace
  namespace: dev
spec:
  loadBalancer:
    # Chnage name
    name: nginx
    dcslug: innoida
    # Chnage exposed extrnal port
    backendPort: 30088
    frontend:
      # Chnage name
      name: nginx
      algorithm: roundrobin
      protocol: tcp
      # loadBalancer port
      port: 80
    type: network
