# permissions for end users to edit uthodns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: uthodns-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: utho-lb-controller
    app.kubernetes.io/part-of: utho-lb-controller
    app.kubernetes.io/managed-by: kustomize
  name: uthodns-editor-role
rules:
- apiGroups:
  - apps.utho.com
  resources:
  - uthodns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.utho.com
  resources:
  - uthodns/status
  verbs:
  - get
