---
apiVersion: apps/v1
kind: Deployment
metadata:
  # Chnage name and label
  name: nginx-deployment
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      # Chnage label
      app: nginx
  template:
    metadata:
      labels:
        # Chnage label
        app: nginx
    spec:
      containers:
        - name: nginx
          # Change container image
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          env:
            # Expose secerets as environment variables
            - name: NGINX_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: username
            - name: NGINX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: password
