---
apiVersion: v1
kind: Service
metadata:
  # Chnage name and namespace
  name: nginx
  namespace: dev
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      # Internal port
      port: 8080
      # app exposed port
      targetPort: 80
      # Chnage exposed port
      # External port
      nodePort: 30088
  type: NodePort
