apiVersion: apps.utho.com/v1alpha1
kind: UthoApplication
metadata:
  name: test-app-alb
spec:
  loadBalancer:
    advancedRoutingRules:
      - aclName: test-rule
        routeCondition: true
        targetGroupNames:
        - test-tg-4
        - test-tg-5
    aclRule:
      - name: test-rule
        conditionType: url_path
        value:
          type: url_path
          data:
            - "/"
            - "/path"
    frontend:
      name: test-fe
      algorithm: roundrobin
      protocol: tcp
      port: 80
    type: application
    dcslug: innoida
    name: test-lb
  targetGroups:
    - health_check_timeout: 5
      health_check_interval: 15
      health_check_path: /
      health_check_protocol: TCP
      healthy_threshold: 2
      name: test-tg-4
      protocol: TCP
      unhealthy_threshold: 3
      port: 30080
    - health_check_timeout: 5
      health_check_interval: 30
      health_check_path: /path
      health_check_protocol: TCP
      healthy_threshold: 2
      name: test-tg-5
      protocol: TCP
      unhealthy_threshold: 3
      port: 30080

    

