apiVersion: apps.utho.com/v1alpha1
kind: UthoDNS
metadata:
  labels:
    app.kubernetes.io/name: uthodns
    app.kubernetes.io/instance: uthodns-sample
    app.kubernetes.io/part-of: utho-lb-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: utho-lb-controller
  name: uthodns
spec:
    domain: animesh.com
    records:
    - hostname: "www"
      ttl: 300
      type: A
      value: 1.1.1.1

