name: Build and Push Docker Image

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          docker build -t utho/utho-app-operator:${{ env.VERSION }} .
          docker tag utho/utho-app-operator:${{ env.VERSION }} utho/utho-app-operator:latest

      - name: Push Docker image with version tag
        run: docker push utho/utho-app-operator:${{ env.VERSION }}

      - name: Push Docker image with latest tag
        run: docker push utho/utho-app-operator:latest
